### ISSUE TITLE
rename `master` branch to `main`

### ISSUE THREAD

**Issue by joseluis** [dankamongmen/notcurses-rs#4]
I have no permissions for this. Maybe @dankamongmen can you do it? No hurries

**Comment by dankamongmen** [comment]
i'm looking at my checkout, and it seems we're already on `main`?

```
[schwarzgerat](0) $ git branch -l
* main
[schwarzgerat](0) $ pwd
/home/dank/src/dankamongmen/libnotcurses-sys
[schwarzgerat](0) $ git remote -v
origin	git@github.com:dankamongmen/libnotcurses-sys.git (fetch)
origin	git@github.com:dankamongmen/libnotcurses-sys.git (push)
[schwarzgerat](0) $ 
```

**Comment by dankamongmen** [comment]
i don't think any scripts in `dankamongmen/notcurses` refer to this, so i've got no problem with it. let me know if i need to do anything. ideally you ought have permissions to do this; let me take a look.

**Comment by dankamongmen** [comment]
i used the github UI to change the "default" branch to `main` from `master`. i think that's all that's necessary?

i'd prefer to leave things as they are in `dankamongmen/notcurses`, but i think your goals are accomplished here. closing this up; feel free to reopen if necessary.

**Comment by joseluis** [comment]
Yeah, that was it! just on this repo, thanks mate!
